### PR TITLE
Js unit testing

### PR DESCRIPTION
**Pull request by nomicflux**
Added Teaspoon and Jasmine for js unit testing, with additional lines in the Gemfile and bin/setup to facilitate setup

Added a couple specs to spec/javascripts/, just to test out testing framework (run with bin/rake teaspoon once server is running, with results accessible at http://server:port/teaspoon).

Hopefully I didn't make to much of a mess of things; this was my first pull request, so I apologize if there are too many commits in it.

ToDo: Writing the actual specs, once the base here is accepted.

### CODE REVIEW

**Comment by botandrose** [comment]
Awesome! I'm very excited to see some interest in improving the state of affairs, here.

I see the Travis test run has failed, and I'm pretty sure its because the `Gemfile.lock` was removed in one of the commits. This file should definitely be in the repo.

**Comment by nomicflux** [comment]
Oops, Gemfile.lock now added.  Let's see if that works.

**Comment by botandrose** [comment]
Okay, we're green again! This is looking good.

One more thing: I see that you've added the teaspoon installation to `bin/setup`, but I don't think that really makes sense there, because `rails g teaspoon:install` just generates fresh copies of `spec/spec_helper.js` and `spec/teaspoon_env.rb`, and you've already committed modified copies of those to the repo, so every time `bin/setup` is run, it would just try to overwrite them. So, I think if you remove the changes to `bin/setup`, this will be good to merge.

Lastly, if you could rebase squash all these commits down to one, that'd be great. But not a big deal, if not.

**Comment by nomicflux** [comment]
Ok, looks like that worked!  Hopefully the rebase didn't get too messy.

**Comment by botandrose** [comment]
:shipit:

**Comment by botandrose** [comment]
Thanks! I'm going to add a commit to integrate teaspoon into the CI run, so that we know if any of the tests fail.

**Comment by botandrose** [comment]
Okay, master has teaspoon integrated into its test run, and is green! :tada:

**Pull request merged**
